### ISSUE TITLE
null-coalescing assignment operator split up breaking compilation - fixed in uncrustify

### ISSUE THREAD

**Issue by ArchyInf** [Unity-Technologies/uncrustify#162]
Uncrustify-0.67-984-942104e9

Example file
```
public class Foo
{
    public void Bar()
    {
        object x;
        x ??= new String();
    }
}
```

Space is added between ?? and = resulting in compilation error.

This issue was fixed in uncrustify a while ago:
[add support for C# 8 null-coalescing assignment operator](https://github.com/uncrustify/uncrustify/commit/545c13f42f291aca40230ef32942d4ef7d844f7b#diff-599e41142c27f5f20a71fd5f8b8018a68b5036aafa6f7f1282a0ecdbca18161d)

**Comment by mihaipopescu** [comment]
Thank you for reporting. The issue was fixed on our own side as well in #160 by @tomekpaszek.
Unfortunately our fork has diverged a lot from the upstream and a down merge will be difficult. Still, it would be a very good thing to do and upstream all of our work.
