### ISSUE TITLE
Regression on PR 31 for cascading assignments

### ISSUE THREAD

**Issue by Rassi** [Unity-Technologies/uncrustify#37]
PR 31 introduced regressions for cascading assignments, not indenting them past the second assignment.

https://github.com/Unity-Technologies/uncrustify/pull/31#issuecomment-339662104

Expected versus output diff:
---
```diff
diff --git "a/C:\\dev\\uncrustify\\tests\\output\\staging\\60038-UNI-30088.cpp" "b/C:\\dev\\uncrustify\\tests\\results\\staging\\60038-UNI-30088.cpp"
index 1fd5c1f..6a2d3d8 100644
--- "a/C:\\dev\\uncrustify\\tests\\output\\staging\\60038-UNI-30088.cpp"
+++ "b/C:\\dev\\uncrustify\\tests\\results\\staging\\60038-UNI-30088.cpp"
@@ -1,9 +1,9 @@
 void Foo(int value)
 {
     m_Foo[0].prop
-        = m_Foo[1].prop
-            = m_Foo[2].prop
-                = m_Foo[3].prop
-                    = m_Foo[4].prop
-                        = m_Foo[5].prop = value;
+	= m_Foo[1].prop
+		= m_Foo[2].prop
+			= m_Foo[3].prop
+				= m_Foo[4].prop
+					= m_Foo[5].prop = value;
 }
```

Debug support files:
---
[60038-UNI-30088.cpp](https://gist.githubusercontent.com/Rassi/4871d1793e311803531c374d942a16be/raw/366f260821cddba374ab6f5c2b4fdd432028d4c5/60038-UNI-30088.cpp)
[60038-UNI-30088.cpp.log](https://gist.githubusercontent.com/Rassi/4871d1793e311803531c374d942a16be/raw/374e769b550df96509ef644a35fbe234161775ac/60038-UNI-30088.cpp.log)
[60038-UNI-30088.cpp.unc](https://gist.githubusercontent.com/Rassi/4871d1793e311803531c374d942a16be/raw/8ba4fdb0b9fda7ff2b5f6f7a6a180de9927507ae/60038-UNI-30088.cpp.unc)
[UNI-30088.cfg](https://gist.githubusercontent.com/Rassi/4871d1793e311803531c374d942a16be/raw/1a217ed1580ad668a4119e752c30d451800743d5/UNI-30088.cfg)
[UNI-30088.cpp](https://gist.githubusercontent.com/Rassi/4871d1793e311803531c374d942a16be/raw/366f260821cddba374ab6f5c2b4fdd432028d4c5/UNI-30088.cpp)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by Rassi** [comment]
Issue created with wrong executable. Closing and creating new.

**Comment by unitydevtools** [comment]
test
